version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpods
      POSTGRES_PASSWORD: "E00aZ2JVLXLkj4hHBO3BHl7M36y65Kbb"
    volumes:
      - serverpods_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Ju5_SngvlFyheAITOalZrBW18otwPGy1"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  serverpods_data:
